spring.application.name=LearningPlatformValidation


# Configuración de la base de datos Oracle Cloud (Autonomous Database)
# Se mantienen las credenciales visibles por ser un entorno académico.
# En un entorno productivo se deben usar variables de entorno o un vault de secretos.

spring.datasource.url=jdbc:oracle:thin:@(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.sa-santiago-1.oraclecloud.com))(connect_data=(service_name=g4aeeedcd76386f_springdb_tp.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
spring.datasource.username=ADMIN
spring.datasource.password=MiPassword123#
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10